# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT.xci
# IP: The module: 'DSP48_AaC1_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48_AaC1_LUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT.xci
# IP: The module: 'DSP48_AaC1_LUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48_AaC1_LUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
