# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk.xci
# IP: The module: 'DSP48E1_AaDmB_2clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48E1_AaDmB_2clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk.xci
# IP: The module: 'DSP48E1_AaDmB_2clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48E1_AaDmB_2clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
