# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.cache/wt [current_project]
set_property parent.project_path C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/imports/pic2txt/7dX.coe
add_files C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/imports/pic2txt/7dXS.coe
read_verilog -library xil_defaultlib {
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/AdderTree.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/AverageTree.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/MaxTree.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/Mul_8bit_4bit.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/Mul_Add_Tree.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/add_quant.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/bias_load.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/conv.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/conv_t.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/matrix_multiplication.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/pooling.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/pooling_t.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/ps_simulator.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/weight_load.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/window.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/window_t.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/beat.v
  C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MATRIX_BRAM_32BIT_512DEEP/FIFO_MATRIX_BRAM_32BIT_512DEEP.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MATRIX_BRAM_32BIT_512DEEP/FIFO_MATRIX_BRAM_32BIT_512DEEP.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MATRIX_BRAM_32BIT_512DEEP/FIFO_MATRIX_BRAM_32BIT_512DEEP_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MATRIX_BRAM_32BIT_512DEEP/FIFO_MATRIX_BRAM_32BIT_512DEEP_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP/FIFO_ADD_QUANT_MAP_BRAM_32BIT_512DEEP_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MAP_BRAM_32BIT_512DEEP/FIFO_MAP_BRAM_32BIT_512DEEP.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MAP_BRAM_32BIT_512DEEP/FIFO_MAP_BRAM_32BIT_512DEEP.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MAP_BRAM_32BIT_512DEEP/FIFO_MAP_BRAM_32BIT_512DEEP_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_MAP_BRAM_32BIT_512DEEP/FIFO_MAP_BRAM_32BIT_512DEEP_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_BIAS_DRAM_16BIT_16DEEP/FIFO_BIAS_DRAM_16BIT_16DEEP.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_BIAS_DRAM_16BIT_16DEEP/FIFO_BIAS_DRAM_16BIT_16DEEP.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_BIAS_DRAM_16BIT_16DEEP/FIFO_BIAS_DRAM_16BIT_16DEEP_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_BIAS_DRAM_16BIT_16DEEP/FIFO_BIAS_DRAM_16BIT_16DEEP_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/rom_pic/rom_pic.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/rom_pic/rom_pic_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AaC1_LUT/DSP48_AaC1_LUT_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48E1_AaDmB_2clk/DSP48E1_AaDmB_2clk_ooc.xdc]

read_ip -quiet C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xci
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/constrs_1/new/PCNN.xdc
set_property used_in_implementation false [get_files C:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/constrs_1/new/PCNN.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg400-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
