# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xci
# IP: The module: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xci
# IP: The module: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/FIFO_WEIGHT_BRAN_32BIT_512DEEP/FIFO_WEIGHT_BRAN_32BIT_512DEEP_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_WEIGHT_BRAN_32BIT_512DEEP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
