# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/rom_pic/rom_pic.xci
# IP: The module: 'rom_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/rom_pic/rom_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pic'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/rom_pic/rom_pic.xci
# IP: The module: 'rom_pic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN/PCNN/PCNN.srcs/sources_1/ip/rom_pic/rom_pic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pic'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
