# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1.xci
# IP: The module: 'DSP48_AmBW1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48_AmBW1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1.xci
# IP: The module: 'DSP48_AmBW1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/IC_1101/Desktop/PCNN_4bit/PCNN_4bit/PCNN_4bit.srcs/sources_1/ip/DSP48_AmBW1/DSP48_AmBW1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DSP48_AmBW1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
